keybindings:
    # Ctrl+Win+Arrows = 1/2 screen
    - modifier: [Ctrl, Win]
      key: LEFT_ARROW
      bindfeature: leftHalf
    - modifier: [Ctrl, Win]
      key: RIGHT_ARROW
      bindfeature: rightHalf
    - modifier: [Ctrl, Win]
      key: UP_ARROW
      bindfeature: moveToCenter
    - modifier: [Ctrl, Win]
      key: DOWN_ARROW
      bindfeature: bottomHalf

    # Ctrl+Alt+Shift+Arrows = 2/3 screen
    - modifier: [Ctrl, Alt, Shift]
      key: LEFT_ARROW
      bindfeature: leftTwoThirds
    - modifier: [Ctrl, Alt, Shift]
      key: RIGHT_ARROW
      bindfeature: rightTwoThirds
    - modifier: [Ctrl, Alt, Shift]
      key: UP_ARROW
      bindfeature: moveToCenter
    - modifier: [Ctrl, Alt, Shift]
      key: DOWN_ARROW
      bindfeature: bottomTwoThirds

    # Ctrl+Win+Shift+Arrows = 1/3 screen
    - modifier: [Ctrl, Win, Shift]
      key: LEFT_ARROW
      bindfeature: leftOneThirds
    - modifier: [Ctrl, Win, Shift]
      key: RIGHT_ARROW
      bindfeature: rightOneThirds
    - modifier: [Ctrl, Win, Shift]
      key: UP_ARROW
      bindfeature: moveToCenter
    - modifier: [Ctrl, Win, Shift]
      key: DOWN_ARROW
      bindfeature: bottomOneThirds
