keybindings:
    # Ctrl+Win+Arrows = 1/2 screen
    - modifier: [Ctrl, Win]
      key: LEFT_ARROW
      bindfeature: leftHalf
    - modifier: [Ctrl, Win]
      key: RIGHT_ARROW
      bindfeature: rightHalf
    - modifier: [Ctrl, Win]
      key: UP_ARROW
      bindfeature: centerHalf
    - modifier: [Ctrl, Win]
      key: DOWN_ARROW
      bindfeature: bottomHalf

    # Ctrl+Alt+Shift+Arrows = 3/4 screen
    - modifier: [Ctrl, Alt, Shift]
      key: LEFT_ARROW
      bindfeature: leftThreeQuarters
    - modifier: [Ctrl, Alt, Shift]
      key: RIGHT_ARROW
      bindfeature: rightThreeQuarters
    - modifier: [Ctrl, Alt, Shift]
      key: UP_ARROW
      bindfeature: centerThreeQuarters
    - modifier: [Ctrl, Alt, Shift]
      key: DOWN_ARROW
      bindfeature: bottomThreeQuarters

    # Ctrl+Win+Shift+Arrows = 1/4 screen
    - modifier: [Ctrl, Win, Shift]
      key: LEFT_ARROW
      bindfeature: leftOneQuarter
    - modifier: [Ctrl, Win, Shift]
      key: RIGHT_ARROW
      bindfeature: rightOneQuarter
    - modifier: [Ctrl, Win, Shift]
      key: UP_ARROW
      bindfeature: center
    - modifier: [Ctrl, Win, Shift]
      key: DOWN_ARROW
      bindfeature: bottomOneQuarter
